#!/usr/bin/python3
#-*-coding:UTF-8-*-
def odd_or_even(i):
    if i%2==0:
        print('%d is an even number'%i)
    else:
        print('%d is an odd number'%i)
def isdigit(a):
    try:
        int(a)
   ##
        return True
    except:
        return False
num=input("请输入一个整数：")
assert isdigit(num),"您输入的不是整数！"
odd_or_even(int(num))
