#!/usr/bin/python3
#-*-coding:UTF-8-*-

print("九九乘法表:")
print("左下三角型")
for i in range(1,10):
    for j in range(1,i+1):
        print('%d*%d=%2d'%(j,i,i*j),end=" ")
#换行
    print("")
print('左上三角型')
for i in range(1,10):
    for j in range(i,10):
        print('%d*%d=%2d'%(i,j,i*j),end=" ")
    print("")
print('右下三角型')
for i in range(1,10):
    for k in range(1,10-i):
        print(end="       ")
    for j in range(1,i+1):
        print('%d*%d=%2d'%(j,i,i*j),end=" ")
    print("")
print('右上三角型')
for i in range(1,10):
    for k in range(1,i):
        print(end="       ")
    for j in range(i,10):
        print('%d*%d=%2d'%(i,j,i*j),end=' ')
    print("")
print("矩形")
for i in range(1,10):
    for j in range(1,10):
        print('%d*%d=%2d'%(i,j,i*j),end=" ")
    print("")
